### ISSUE TITLE
Message on disks in status view

### ISSUE THREAD

**Issue by Ekerim** [45Drives/cockpit-zfs-manager#7]
On Rocky 8 (RHEL8) the message '/dev/(null' is shown as a message for each disk in the status view.
![zfs msg](https://user-images.githubusercontent.com/1951482/168049807-ef472373-d550-4013-8346-aee400efe102.png)

**Comment by bkelly16** [comment]
This is related to this [issue](https://github.com/openzfs/zfs/pull/13436) over in the openzfs repo. 

Root cause is still under investigation and will need to be fixed in openzfs source, but in the meantime this workaround should get the job done until its fixed upstream.

1. Make a directory for custom zpool helper scripts
```mkdir /root/.zpool.d```
2. Curl down this helper script, and mark it as executable 
```curl -o /root/.zpool.d/upath https://scripts.45drives.com/zfs/upath && chmod +x /root/.zpool.d/upath```
3. Verify you can see the /dev/sd* names in the upath column
```ZPOOL_SCRIPTS_AS_ROOT=1 zpool status -p -t -c upath```
4. Verify in the UI, the message column should be empty and the correct device model info will be under the Product Column
  
![Screenshot from 2022-05-16 16-17-48](https://user-images.githubusercontent.com/19629309/168666192-cac72d6b-ce99-429e-8701-c41adcf3c04c.png)

**Comment by Ekerim** [comment]
Thank you.

Worked as it should.
